export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";  
export const GET_ADMIN = "GET_ADMIN";
export const GET_EMPLOYEE = "GET_EMPLOYEE";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE"
export const PROFILE_LOADING = "PROFILE_LOADING";
export const GET_USER_DETAIL = "GET_USER_DETAIL"