const mongoose = require('mongoose');

const Schema = mongoose.Schema;

const UserSchema = new Schema({
    loanId: {
        type:Number,
        required:true
    },
    loanStartDate:{
        type:Date,
        required:true
    }, 
    Name:{
        type:String,
        required:true
    },
    Age:{
        type:Number,
        required:true
    },
    loanType:{
        type:String,
        required:true
    },
    DOB:{
        tyep:Date,
        required:true
    },
    PAN:{
        type:String,
        required:true,
        maxlength:10
    },
    AdharCard:{
        type:Number,
        required:true,
        maxlength:12
    },
    gender:{
        type:String,
        required:true
    },
    Address:{
        type:String,
        required:true
    },
    state:{
        type:String,
        required:true
    },
    pincode:{
        type:Number,
        required:true,
        maxlength:6
    },
    mobileNumber:{
        type:Number,
        required:true,
        maxlength:10
    },
    loanAmount:{
        type:Number,
        required:true
    },
    disbursalAmount:{
        type:Number,
        required:true
    },
    pendingDisbursalAmount:{
        type:Number,
        required:true
    },
    pendingPayment:{
        type:Number,
        required:true
    },
    netPayable:{
        type:Number,
        required:true
    },
    intrestRate:{
        type:Number,
        required:true
    },
    installmentAmount:{
        type:Number,
        required:true
    },
    repayFreq:{
        type:String,
        required:true
    },
    expiry:{
        type:String,
        required:true
    },
    Branch:{
        type:String,
        required:true
    },
    repayment:[
        {
            Name:{
                type:Schema.Types.ObjectId,
                ref:'user'
            },
            loanId:{
                type:Schema.Types.ObjectId,
                ref:'user'
            },
            Method:{
                type:String,
                required:true
            },
            CollectedBy:{
                type:String,
                required:true
            },
            collectedDate:{
                type:String,
                required:true
            },
            paidAmount:{
                type:String,
                required:ture
            }
        }
    ],
    ClosedOn:{
        type:Date,
        required:true
    },
    ClosedReason:{
        type:String,
        required:true
    }
})

module.export = User = mongoose.model('user',UserSchema)